### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by nishuihanlong** [yanshengjie/LearningMpaAbp#2]
我看到你的action都用ValidateAntiForgeryToken特性关闭跨域请求攻击保护了，这样不是违反abp初衷了吗？我也是没什么好的解决方案

**Comment by sheng-jie** [comment]
> 我看到你的action都用ValidateAntiForgeryToken特性关闭跨域请求攻击保护了，这样不是违反abp初衷了吗？我也是没什么好的解决方案

[ValidateAntiForgeryToken]特性是Asp.net mvc自带的用来进行CSRF保护的特性。
Abp对CSRF进行了开箱即用的集成，允许我们不必再为Action设置[ValidateAntiForgeryToken]特性。
代码中[ValidateAntiForgeryToken]特性可能是我用脚手架自动生成的，所以就没有去掉。
添加这个特性[ValidateAntiForgeryToken]也不会关闭CSRF保护吧，毕竟ABP集成的一套CSRF保护机制还是会正常工作的。
具体可参考：
https://github.com/ABPFrameWorkGroup/AbpDocument2Chinese/blob/master/Markdown/Abp/6.9CSRF%E5%92%8CXSRF%E4%BF%9D%E6%8A%A4.md

**Comment by nishuihanlong** [comment]
thank you,参考你的很多方式
